#---
#  tasks:
#    - name: Getting join command
#      shell: cat /tmp/logs/cluster_init.log | grep 'kubeadm join 192.168.4.224' | sed -e 's/^  //g'
#      register: join_cmd
#      when: inventory_hostname in groups['kubernetes-master']
#   
#    - name: Joining cluster
#      debug: 
#        msg: "{{ join_cmd }}"

#    - set_fact: join_command="{{ join_cmd.stdout }}"
   
#    - debug: 
#        msg="{{ hostvars['kubernetes-node']['join_command.stdout'] }}"
