---
 - name: Setup Hostname
   hostname:
     name: {{ hostvars[kubernetes-master].inventory_hostname }}

 - name: Setup /etc/hosts
      lineinfile:
        dest: /etc/hosts
        line: "{{ hostvars[item].ansible_host }} {{ hostvars[item].inventory_hostname }} {{ hostvars[item].inventory_hostname_short }}"
        state: present
      with_items: "{{ groups.all }}"

 - name: ansible create logs directory
   file:
     path: "{{ log_dir }}"
     state: directory
     mode: 644

 - name: Getting cgroups information
   shell: "docker info | grep -i cgroup | awk -F ': ' '{print $2}'"
   register: cgroup_name

 - name: Update Kubeadm configuration file
   template:
     src: files/10-kubeadm.conf.j2
     dest: files/10-kubeadm.conf
   vars:
     cgroup_driver: "{{ cgroup_name }}"

 - name: Initialize Cluster
   shell: 'kubeadm init --apiserver-advertise-address="{{ master_address }}" --pod-network-cidr="{{ pod_network_cidr }}" | tee -a "{{ log_dir }}"/cluster_init.log'

 - name: Create local configuration directory
   file:
     path: "{{ kube_home_dir }}"
     state: directory
     owner: root
     group: root

 - name: Copy kubeadm configuration file
   copy:
     src: "{{ kube_admin_conf }}"
     dest: "{{ kube_config }}"
     owner: root
     group: root

 - name: Stop Kubelet Service
   systemd:
     state: stopped
     name: kubelet

 - name: Copy kubeadm init file
   copy:
     src: "{{ kubeadm_init_template_src }}"
     dest: "{{ kubeadm_init_dest }}"
     owner: root
     group: root
     backup: yes

 - name: Reload daemon
   systemd:
     state: restarted
     daemon_reload: yes
     name: kubelet

 - name: Pause for 30 seconds
   pause:
     seconds: 30

 - name: Apply Flannel Network
   shell: kubectl apply -f "{{ flannel_yaml }}" | tee -a "{{ log_dir }}"/flannel.log

 - name: Pause for 30 seconds
   pause:
     seconds: 30

 - name: Check Status of node
   shell: kubectl get nodes -o wide | tee -a "{{ log_dir }}"/nodes.log

 - name: Apply kubectl dns ConfigMap
   shell: kubectl apply -f "{{ config_map_yaml }}"

 - name: Pause for 10 seconds
   pause:
     seconds: 10
    
 - name: Check pod status
   shell: kubectl get pods -n kube-system -o wide | tee -a "{{ log_dir }}"/pods.log
   
 - name: Taint Master node
   shell: kubectl taint node "{{ ansible_hostname }}" node-role.kubernetes.io/master:NoSchedule-
