---
# vars file for kube-single-node
kube_home_dir: ~/.kube
kube_admin_conf: /etc/kubernetes/admin.conf
kube_config: ~/.kube/config
kubeadm_init_template_src: '{{ role_path }}/files/10-kubeadm.conf'
kubeadm_init_dest: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
log_dir: /tmp/logs
config_map_yaml: '{{ role_path }}/files/configmap.yml'
flannel_yaml: "https://raw.githubusercontent.com/coreos/flannel/v0.10.0/Documentation/kube-flannel.yml"
